sudo: required
services:
    - docker

before_install:
    - docker build -t vedhaaa/react-test -f ./client/Dockerfile.dev .

script:
    - docker run -e CI=true vedhaaa/react-test npm test -- --coverage
after_success:
    - docker build -t vedhaaa/multi-client ./client
    - docker build -t vedhaaa/multi-nginx ./nginx
    - docker build -t vedhaaa/multi-server ./server
    - docker build -t vedhaaa/multi-worker ./worker
    #Login to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #take those docker images push them to docker hub
    - docker push vedhaaa/multi-client
    - docker push vedhaaa/multi-nginx
    - docker push vedhaaa/multi-server
    - docker push vedhaaa/multi-worker